version: '3.9'

services:
  video-db:
    image: mongo:5.0.7-focal
    restart: always
    ports:
      - 27018:27017

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    
  rabbitmq:
    image: rabbitmq:3.10.0-rc.4-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  user-db:
    image: postgres:12.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: userDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456